name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build binaries
        run: make

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            outputs/awz-buddy-linux-amd64
            outputs/awz-buddy-windows-amd64.exe
            outputs/awz-buddy-darwin-amd64
            outputs/awz-buddy-darwin-arm64

      - name: Create GitHub Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: outputs/awz-buddy-linux-amd64
          asset_name: awz-buddy-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin amd binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: outputs/awz-buddy-darwin-amd64
          asset_name: awz-buddy-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin arm binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: outputs/awz-buddy-darwin-arm64
          asset_name: awz-buddy-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: outputs/awz-buddy-windows-amd64.exe
          asset_name: awz-buddy-windows-amd64.exe
          asset_content_type: application/octet-stream
