name: Build & Release

on:
  push:
    tags:
      - "v*"


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build binaries
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/awz-buddy-linux-amd64
          asset_name: awz-buddy-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin amd binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/awz-buddy-darwin-amd64
          asset_name: awz-buddy-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin arm binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/awz-buddy-darwin-arm64
          asset_name: awz-buddy-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/awz-buddy-windows-amd64.exe
          asset_name: awz-buddy-windows-amd64.exe
          asset_content_type: application/octet-stream
