name: Build & Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build binaries
        run: make

      - name: Create GitHub Release with assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
