name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build binary
        run: make

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            outputs/awz-buddy-linux-amd64
            outputs/awz-buddy-windows-amd64.exe
            outputs/awz-buddy-darwin-amd64
            outputs/awz-buddy-darwin-arm64
